---
- name: Recreate the devenv
  hosts: localhost
  vars_files:
    - vars/devlab-pve.yml
    - vaults/vault.yml
    - vars/devenv1.yml
  roles:
    - pve_purge
    - pve_lxc_create

- name: Configure the devenv
  hosts: devenv1
  vars_files:
    - vaults/vault.yml
    - vars/devenv1.yml
  roles:
    - base